"""Initial PostgreSQL migration

Revision ID: d82ecb23d2d1
Revises: 
Create Date: 2026-08-04 12:54:31.128651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82ecb23d2d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_pagar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centro_custo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_conta_pagar_centro_custo_id_centro_custo'), 'centro_custo', ['centro_custo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_pagar', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conta_pagar_centro_custo_id_centro_custo'), type_='foreignkey')
        batch_op.drop_column('centro_custo_id')

    # ### end Alembic commands ###
